# Generated by Django 3.0.5 on 2020-04-26 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_jobs_key'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jobs',
            new_name='jobsInfo',
        ),
    ]
