# Generated by Django 3.0.5 on 2020-04-27 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20200426_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobsinfo',
            name='organization',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='jobsinfo',
            name='salary',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='jobTitle',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='link',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='place',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='site',
            field=models.TextField(default=None),
        ),
    ]
