# Generated by Django 3.0.5 on 2020-04-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20200427_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsinfo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='jobTitle',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='link',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='organization',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='place',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='salary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='site',
            field=models.TextField(blank=True, null=True),
        ),
    ]
