# Generated by Django 3.0.5 on 2020-04-27 20:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20200427_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobsinfo',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='jobTitle',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='organization',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='place',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='salary',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobsinfo',
            name='site',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
