# Generated by Django 3.0.5 on 2020-04-27 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20200427_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobsinfo',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='jobsinfo',
            name='salary',
        ),
    ]
